id: rida
name: "Ride & Dash: Airbikes"
author: Geegaz
version: dev

data_pack:
  load:
    - src
  min_format: 101
  max_format: 107
  zipped: false
resource_pack:
  load:
    - src
  min_format: 84
  max_format: 88
  zipped: false

output: build

require:
  - beet.contrib.extra_files
  - beet.contrib.unknown_files
pipeline:
  - plugins.generate_font_assets
  - plugins.generate_ship_assets
  - beet.contrib.babelbox
meta:
  babelbox:
    load: translations.csv
    namespace: rida
  ships_file: src/ships.json
  extra_files:
    data_pack:
      - LICENSE_datapack.md
    resource_pack:
      - LICENSE_resourcepack.md